<Interface>
Interface:
    Button:
        text: "Blue"
        pos: 525, 300
        size: 200,100
        color: "white"
        background_color: 0,0,255

    Button:
        text: "Red"
        pos: 300, 300
        size: 200,100
        color: "white"
        background_color: 255,0,0

    Button:
        text: "Green"
        pos: 75, 300
        size: 200,100
        color: "white"
        background_color: 0,255,0